name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      buildArgs:
        required: true
        type: string
      artifactName:
        required: true
        type: string
      artifactPath:
        required: true
        type: string

env:
  HAXE_VERSION: 4.3.6
  PROJECT_NAME: Funkin

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Install libVLC
        if: contains(inputs.name, 'Linux')
        run: sudo apt install libvlc-dev libvlccore-dev

      - name: Install Libraries
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet
      
      - name: Get Submodules
        run: |
          git submodule update --init --recursive

      - name: Compile
        run: haxelib run lime build ${{ inputs.buildArgs }}

      - name: idk
        if: inputs.name == 'HTML5'
        run: |
          cd export/release/html5/bin
          git init
          git add .
          git commit -m "updateletsgoo"
          git remote add origin https://github.com/ant6723/fnf
          git push -u origin main
