name: Build + Release
on: workflow_dispatch

permissions:
  contents: write
  discussions: write

env:
  PROJECT_NAME: Funkin

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: HTML5
            os: macos-15
            buildArgs: "html5 -DFEATURE_GHOST_TAPPING"
            artifactName: Html5build
            artifactPath: "export/release/html5/bin/*.zip"
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
           name: Html5Build
           path: ${{ github.workspace }}

      - name: Zip iOS Build For Release
        run: zip -r /home/runner/${{ env.PROJECT_NAME }}-HTML5.zip ${{ github.workspace }}/${{ env.PROJECT_NAME }}.zip

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "0.6.2"
          tag_name: "0.6.2"
          prerelease: false
          files: |
            /home/runner/*.zip
